### PR TITLE
Bugfix: e926 download mirror fix

### PR DESCRIPTION
**Pull request by FlipperLP**
There is currently an issue that e926 cant download the pictures. So either you can implement this fix or look into why the download for that site is broken. But it might be an issue on their end.

### CODE REVIEW

**Comment by neobooru** [comment]
Is this still not working for you? Because it seems to work fine on my end (without this change).
I do have `user_agent` inside `szurubooru/server/config.yaml` set to `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36`, maybe that makes a difference?

**Comment by FlipperLP** [comment]
My browser: https://www.whatsmybrowser.org/b/P2T10
The error I get:
`{ "name": "DownloadError", "title": "Processing error", "description": "https://static1.e926.net/data/5e/52/5e52ce1d420a565dc600cc6d2523fa9b.png" }`

**Comment by neobooru** [comment]
The szurubooru instance has to download the images itself, we only send and imageUrl to the szurubooru instance. e926 verifies that you have a 'legit' user-agent, which szurubooru by default _does not_ have. I think that you'd solve your issue when you set the `user_agent` value to some legit value (you can copy mine, or copy yours from your link).

**Comment by FlipperLP** [comment]
Alright, that did indeed work. That might also fix some other download issues I had with other websites. Anyways, you may close this PR if you don't think its needed.

**Pull request closed without merging**
