### PR TITLE
added Furaffinity scraper

### PR DESCRIPTION
**Pull request by FlipperLP**
Please review the code, before merging.
I am by far not an expert in TS as well as even less in browser add-ons. That caused me to just copy existing code (based on e621) and modify it.
As I also don't know fully your setup to debug the application, I wasn't able to fully do that. So you might need to test around first.
imma test around and use it to add some of the arts I liked to szuru and let you know if there are any issues.

On top of that There would be a species category, but for simplicity’s sake and not enough knowledge about JS and TS, I left it out for now.

### CODE REVIEW

**Comment by FlipperLP** [comment]
Ok, for some reason, GitHub added the changes from yesterday to this PR as well...

**Comment by neobooru** [comment]
I'll look at this soon. I'll also add a section in the readme which describes how you can setup an development environment. I always use SzuruChrome to test this library, but it takes a few extra steps to use your modified version over the published package.

**Comment by FlipperLP** [comment]
> 
> 
> I'll look at this soon. I'll also add a section in the readme which describes how you can setup an development environment. I always use SzuruChrome to test this library, but it takes a few extra steps to use your modified version over the published package.

I just used the `build` in npm scripts you provided and added the programs that were needed to run them. For the package, I uninstalled it and used the `npm link` functionality to add my modified local dependency. But as I said earlier, never was able to really debug it live, like I'm used to it with my discord bots.

**Comment by neobooru** [comment]
Ah yeah that is what I do too. Debugging it live is possible, but I wouldn't know how. I usually just open the browser's dev window (F12) in either the extension popup, content page, or the background page (they all have a different purpose). In the devtools you can also set breakpoints, but its still harder to use than say the vscode debugger.

**Comment by FlipperLP** [comment]
I tried that... and.. It didn't stop where I wanted to. But it might be because I had the wrong file.. Any ways. I got it to work with looking at other code, looking at my old shitty code and blind trail and error scraping.

**Comment by FlipperLP** [comment]
Is it important, that the tags need to be lowercase, because the code doesn't do that yet.

**Comment by neobooru** [comment]
No, that is just personal preference. I guess I could make a setting for that?

**Comment by FlipperLP** [comment]
I don't think it's necessary. The tags get put in lowercase til they are in szurubooru.

**Comment by FlipperLP** [comment]
Are you still planing to push an update for this?

**Comment by neobooru** [comment]
Sorry, I pretty much forgot about this. I manually merged this and updated SzuruChrome too.

**Pull request closed without merging**
